### ISSUE TITLE
oidc / 2x browser login

### ISSUE THREAD

**Issue by msalle** [WLCG-AuthZ-WG/client-tools#3]
We should probably note that even if the user needs to login twice, the SSO should or could make that pretty much transparent.

**Comment by DrDaveD** [comment]
I disagree that it would be transparent.  The user still has to go to the web browser twice, even if the second time they don't need to login.  The first time they would need to log in, and the second time they would need to authorize the application.

**Comment by msalle** [comment]
Disclaimer: I'm not per se in favour of one of the two solutions.

Not sure I fully know the oidc-agent flow well enough, but the htgettoken flow also shows me quite a few pages:

- request for a user certificate at WLCG IAM
- login page WLCG IAM
- CERN SSO -> choose eduGAIN
- WAYF page -> choose home IdP
- home IdP SSO
- consent/inform home IdP
- approval WLCG IAM client

I don't think these steps are easily preventable, and I agree it's in this case a single browser-flow, but I feel it's not really that different from oidc-agent.

**Comment by DrDaveD** [comment]
It is different, because if we need to first register a dynamic client the user would need to go the browser twice.  The first time will be all but the last step, and the second time will be the last step only because the previous steps should have been saved in a cookie.  The user will need to paste two URLs into their web browser.
